### ISSUE TITLE
[BUG] file dark_oak_trapdoor_top has no texture CLASSIC 3D MC ver. 1.19

### ISSUE THREAD

**Issue by NoHyblitz** [RyanGar46/Classic-3D#13]
**READ THIS**
**Please put the labels that best fit with this bug. For example put "Classic 3D - Lite" if it only applies to classic 3d lite.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Minecraft Version: 1.17
 - Classic 3D Version: v13.0

**Additional context**

**Comment by RyanGar46** [comment]
Duplicates #12
