### ISSUE TITLE
Horizontal hay block is not 3d [Bug]

### ISSUE THREAD

**Issue by Hautzii** [RyanGar46/Classic-3D#14]
**READ THIS**
**Please put the labels that best fit with this bug. For example put "Classic 3D - Lite" if it only applies to classic 3d lite.**

Classic 3D

**Describe the bug**

Horizontal hay block is not 3d. Also when the file hay_block_horizontal is loaded in blockbench you get an error (Empty Child Model : This file is a child of block/cube_column_horizontal and does not contain a model.)

**To Reproduce**

1. Load the pack in game.

**Expected behavior**

I expect all the hay blocks to be 3d regardless of their orientation.

**Screenshots**

https://imgur.com/a/y3SqFmi

**Info (please complete the following information):**
 - Minecraft Version: 1.19
 - Classic 3D Version: Classic+3D+v15.0.b1+-+1.19

**Additional context**

**Comment by RyanGar46** [comment]
This should've been fixed in #15.1

**Comment by Hautzii** [comment]
I'll download this version and check if it works properly

**Comment by Hautzii** [comment]
The new version did fix it but when I transfer the models and the blockstate to another texture pack the issue reappears

**Comment by Hautzii** [comment]
Is there another file I need to copy ? I copied the hay_block.json in the blockstates folder and the hay_block.json / hay_block_horizontal.json in the models folder

**Comment by RyanGar46** [comment]
The only model is hay_block.json. It's rotated with the block state.

**Comment by Hautzii** [comment]
Removed the hay_block_horizontal file but it still doesn't work.

**Comment by Hautzii** [comment]
Resolved the issue myself. My pack is using a .blockstates folder so I had to make another one called blockstates for the horizontal block to work.
