### ISSUE TITLE
[Bug] Some textures are missing or not loading

### ISSUE THREAD

**Issue by Isaac928** [RyanGar46/Classic-3D#19]
![2023-01-20 (5)](https://user-images.githubusercontent.com/123233289/213855584-aa66bcb6-8cd3-4cc2-ac51-124f5f5f7192.png)
![2023-01-20 (6)](https://user-images.githubusercontent.com/123233289/213855619-52250327-83b8-42a6-a6fd-f93b5642a3f4.png)
![2023-01-21](https://user-images.githubusercontent.com/123233289/213856633-1b58d058-0048-41d0-a3fd-6d8b360f9ca0.png)
 
There are more textures, but i didnt feel like finding them all

**Comment by RyanGar46** [comment]
This issue was fixed in bb32b1d74078111616178e3c8693a7523c22f2b4. Sorry about not publishing releases more often. I'm in the process of releasing this now.
