### ISSUE TITLE
Missing Textures on Classic 3D v13.2.1 - 1.17

### ISSUE THREAD

**Issue by Mutinity** [RyanGar46/Classic-3D#2]
I found 3 items that had missing textures. I don't know if there are more but these are the ones I have noticed so far. 

**_Grindstone_** - Not really a big issue but some of the textures on the stand of the grindstone were missing.
![image](https://user-images.githubusercontent.com/68777727/127350048-aa7e6439-af77-44b8-b3f2-2b49320e536c.png)
![image](https://user-images.githubusercontent.com/68777727/127350289-a288ca1d-aa4a-4ea2-91bc-2148d0cd51ff.png)

**_Soul Lantern_** - The soul lantern had a few lines of missing textures but was mostly blacked out all around it.
![image](https://user-images.githubusercontent.com/68777727/127350774-8b226316-361a-49d6-a235-2ad91651228c.png)
![image](https://user-images.githubusercontent.com/68777727/127350800-677ca9cf-a6c6-40e8-a337-2e461c9ed9b4.png)

**_Loom/Tnt_** - The top of the loom/Tnt had the missing textures.
![image](https://user-images.githubusercontent.com/68777727/127351340-8783e964-3fa2-441d-97b9-2df3a75fb560.png)
![image](https://user-images.githubusercontent.com/68777727/127351079-3a853d1d-e305-47a4-8053-839996f2f54f.png)

**_Dirt Path_** - The most noticeable one I have found and it was just all missing textures.
![image](https://user-images.githubusercontent.com/68777727/127351471-5d9b9f60-b765-4e8c-847e-2109faf58fcd.png)
![image](https://user-images.githubusercontent.com/68777727/127351501-01ac7e7c-04bc-46f3-a736-845324eaa5e8.png)

**Comment by RyanGar46** [comment]
This is a issue with the automatic script removing the textures. This is very easy to fix.

**Comment by RyanGar46** [comment]
This was fixed in [v13.3](https://www.curseforge.com/minecraft/texture-packs/classic-3d/files).
