### ISSUE TITLE
Missing textures on  Classic 3D v13.3 - 1.17

### ISSUE THREAD

**Issue by Mutinity** [RyanGar46/Classic-3D#3]
**Describe the bug**
Missing textures on dirt path still.

**Expected behavior**
Even though I have reinstalled the latest version the only missing texture left was the dirt path. I also checked the files if it was there, and there is.

**Screenshots**
![image](https://user-images.githubusercontent.com/68777727/127364936-51d95c48-1b4b-4e65-9bd4-fac7ae7d6bb9.png)

**Info (please complete the following information):**
 - OS: Windows 10 pro
 - Chrome 
 - Minecraft Version 1.17.1
 - Classic 3D Version v13.3

**Comment by RyanGar46** [comment]
Fixed in [v13.3.1](https://www.curseforge.com/minecraft/texture-packs/classic-3d/files)
