### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SylisMC** [RyanGar46/Classic-3D#4]
**Describe the bug**
Noticed stair corner pieces arent 3d for most blocks,

**Info (please complete the following information):**
 - OS W10
 - Minecraft Version 1.17.1
 - Classic 3D Version 13.3.1

![2021-08-18_15 54 09](https://user-images.githubusercontent.com/19602662/129963382-0dc22f62-5e62-415c-aa04-d123a4353cfe.png)

**Comment by SylisMC** [comment]
Copper is the only one ive noticed that is still 3D

**Comment by RyanGar46** [comment]
I have been aware of this. I was going to fix this in 14.0, but thanks for reporting this.

**Comment by SylisMC** [comment]
Perfect! ill go ahead and close this then
