### ISSUE TITLE
[Bug] Dirt Path shows up as a missing texture

### ISSUE THREAD

**Issue by Chill907Gaming** [RyanGar46/Classic-3D#5]
**Describe the bug**
"Dirt Path" shows up as a missing texture and "Poppies" look strange...
I don't expect you to fix this, I can do that myself. :) This I'm more just letting you know it exists.

I fully understand that it's not 100% compatible for this version yet but **_the Non-lite version didn't have the missing path block_**. Because of this I believe it to be a bug with the lite version and must be fixable. 👍 

**To Reproduce**
1. Go to 'Minecraft Version 1.18 experimental snapshot 2'
2. Enable Classic 3D lite texture pack 
3. Create a path block or poppy or both

[**Screenshots**](https://imgur.com/a/bM5jP8T)

**Info (please complete the following information):**
 - OS: [Windows 10 21H1]
 - Minecraft Version: [Experimental 1.18 snapshot 2]
 - Classic 3D Version: [v13.2.1]

**Additional context**
I love this resource pack! I really love the lite version only because the planks and cobble are a little jarring....

**Comment by Chill907Gaming** [comment]
I covered up the issue by simply removing the poopy and path textures and blockstates.

[screenshot](https://imgur.com/a/oN6cPIW) :)

**Comment by RyanGar46** [comment]
This is an issue of parity between the main and lite version. I have an idea of how to get rid of the need to keep parity between lite and main.

Since Classic 3D is built automatically by my RPP tool, I could add the ability to generate the lite version from the main version.

**Comment by RyanGar46** [comment]
This has been fixed in v14.0.
