### ISSUE TITLE
[Bug] Birch Trapdoor Error When Opened - Classic 3D (16x)

### ISSUE THREAD

**Issue by pastyginger** [RyanGar46/Classic-3D#7]
Birch trapdoors give a visual error when right-clicked. 

**- Minecraft Version:** 1.18
**- Classic 3D Version:** v14.0
**- Optifine Version:** 1.18-OptiFine_HD_U_H3

![birch_trapdoor_closed](https://user-images.githubusercontent.com/94149220/144692833-d74d52f6-5504-414f-965c-ffccb0c1dd66.png)
![birch_trapdoor_open](https://user-images.githubusercontent.com/94149220/144692834-e039409d-5db7-4cd1-91d5-bd68d4907737.png)

_Error occurs even with no other resource packs in the load order._

![resource packs](https://user-images.githubusercontent.com/94149220/144692837-b8dcfa7d-0a70-46bd-86ba-51d152a6eaef.png)

This error only seems to occur when the birch trapdoor in its "open" state is intersecting the protruding 3D pieces of a block. Error does not occur when the trapdoor is placed on top of a block, or when it is opened with no blocks behind it to intersect with.

![Open and Intersecting with Block](https://user-images.githubusercontent.com/94149220/144695713-f3bb6a03-ebc3-42b6-987e-7870e16d2127.png)

_Other trapdoors are unaffected._

![Other Trapdoors Unaffected](https://user-images.githubusercontent.com/94149220/144695714-601744ed-0367-4344-aec3-614b3c378bf4.png)

**EDIT:** This is likely an error with the face culling. I've found a temporary fix for the problem by going into assets/minecraft/models/block/birch_trapdoor_open.json and deleting every instance of "cullface" in the code.

Before:

![Before](https://user-images.githubusercontent.com/94149220/144939371-f54a8d13-f683-4cbe-b61a-bcd9b2b8ac4b.png)

After:

![After](https://user-images.githubusercontent.com/94149220/144939395-203b8b34-9e07-4551-97eb-ef53b7e651f6.png)

**Comment by RyanGar46** [comment]
Fixed: https://github.com/RyanGar46/Classic-3D/commit/9fbf3d089dfbad1d28ac82ca290729eb7f919be5
